### ISSUE TITLE
Sync.js doesn't update the oembed endpoint

### ISSUE THREAD

**Issue by NickBlow** [ndaidong/oembed-parser#100]
The sync.js script doesn't seem to handle the case where the oembed endpoint itself has changed. For example, the instagram oembed url is https://graph.facebook.com/v10.0/instagram_oembed.

This is not a problem with the downstream oembed list at `https://oembed.com/providers.json`, as it's correct there.

Is there any reason you don't wholesale just download that list?

**Comment by ndaidong** [comment]
@NickBlow you're right, why not just downloading and overwriting. I believe that nobody customize the providers.json file at their local environment. I will update the sync.js to do that. Thank you.
