### ISSUE TITLE
Wrong default providers list parsing

### ISSUE THREAD

**Issue by CleverMindDev** [ndaidong/oembed-parser#107]
The package, while parsing the providers list does not handle correctly providers with multiple endpoints (like Facebook).
As you can see here: https://github.com/ndaidong/oembed-parser/blob/f85921b2b36023397da3216f56323d24bc4246d4/src/utils/providersFromList.js#L12-L38

Only the first enpoint is handled, while the others are ignored.

**Comment by ndaidong** [comment]
@CleverMindDev you're right, I will try to fix this problem.

**Comment by ndaidong** [comment]
@CleverMindDev please help me test with v2.0.0rc1, thanks
