### ISSUE TITLE
Error: ENOENT: no such file or directory, open './src/utils/providers.json'

### ISSUE THREAD

**Issue by rumbleperson** [ndaidong/oembed-parser#121]
Node Version: `v14.16.1`
Package Version: `v.3.0.0rc1`

#### When importing this package, this error occurs:
Import statement
```javascript
import { hasProvider, extract } from "oembed-parser";
```

Error Message
```
Error: ENOENT: no such file or directory, open './src/utils/providers.json'
```

The issue seems to be the file reference here:

https://github.com/ndaidong/oembed-parser/blob/09c77d97d0a172e3eacecdd2978dedc65b60d679/src/utils/provider.js#L8

**Comment by ndaidong** [comment]
@katyrumble I see, the problem with path. There is a little complicate here. If you are running production, please use stable version instead RC.

**Comment by ndaidong** [comment]
@katyrumble I just released v3.0.0rc2 to fix this issue. You can give it another try if possible. Thanks.

**Comment by styxlab** [comment]
Getting the same error with `v3.0.0rc2`. Am using it with `next.js` so maybe webpack kicks in here. However versions `<3` don't show the issue.

**Comment by ndaidong** [comment]
@styxlab thank you, that's good suggestion to store provider list with js variable. I will take a look into this approach.

**Comment by cclloyd** [comment]
I'm also having this issue with 3.0.0-rc3.  Node 17.5.0

**Comment by ndaidong** [comment]
@styxlab @cclloyd hello friends, v3.0.0rc4 has just been released. Now we don't use `fs` to read data from json file, but access provider list as regular javascript variable. Please give it a try to see if this issue was resolved. Thanks.

**Comment by cclloyd** [comment]
It appears to be fixed.
