### ISSUE TITLE
extract for sway.office.com returns a null

### ISSUE THREAD

**Issue by calin-berindea** [ndaidong/oembed-parser#130]
Hi, I updated to rc5, but when trying to use _extract_ on an https://sway.office.com/ZCftQ83K9iHgOCH0 I get a _null_.
Using _hasProvider_ returns a _true_.

With https://sway.com works correctly.

I tried you demo https://demos.pwshub.com/oembed-parser url and is still giving a _No provider found with given url_ ... error.

**Comment by ndaidong** [comment]
@calin-berindea thank you, let's me try to fix it next release.

**Comment by calin-berindea** [comment]
Hi, any update on this issue? 3.0.0 doesn't fixes it.

**Comment by ndaidong** [comment]
@calin-berindea it's strange! my pr on [iamcal/oembed](https://github.com/iamcal/oembed/pull/621) has been merged, and the latest provider list should include the updates for Sway.

**Comment by calin-berindea** [comment]
Hi @ndaidong 
I just tried it and I get the same behavior, a _null_.
The code is
`
const oembed = await extract(url)
console.log(oembed)
`

I also tried it on the demo page and I get the same result. This is the sway link I'm using 
_https://sway.office.com/ZCftQ83K9iHgOCH0_

![image](https://user-images.githubusercontent.com/99960693/165461388-c8167d72-8db9-409a-a516-c48b8ee627e3.png)

**Comment by calin-berindea** [comment]
Thank you!
Works.

**Comment by ndaidong** [comment]
@calin-berindea thank you, I'm going about to update the demo today.
