### ISSUE TITLE
v3.0.1 introduces an error

### ISSUE THREAD

**Issue by calin-berindea** [ndaidong/oembed-parser#136]
Hi, upgrading from 3.0.0 to 3.0.1 introduces this error.

![image](https://user-images.githubusercontent.com/99960693/164222395-381f832d-319f-4fc4-b43f-c64a89b49860.png)

Thanks

**Comment by ndaidong** [comment]
@calin-berindea thank you for your feedback.
@rcrdlbl hi friend, could you help to fix this issue?

**Comment by ndaidong** [comment]
@calin-berindea I've release v3.0.2, please help me check if this issue is still occurring with your dev environment! Thanks.

**Comment by calin-berindea** [comment]
@ndaidong the update to v3.0.2 is working. Thank you.
