### ISSUE TITLE
Error on electron

### ISSUE THREAD

**Issue by goodhyun** [ndaidong/oembed-parser#14]
`const fetch = require('node-fetch');
`
is causing the following error on an electron/webkit environment

```
 WARNING in ./~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/iconv-loader.js 9:12-34
```
It'd be okay. We can use the browser's built-in fetch. 

What would be a nicer mitigation on this problem than just to comment them out ??

**Comment by ndaidong** [comment]
Please check this issue [#41](https://github.com/bitinn/node-fetch/issues/41) if it gives you some suggestion?
