### ISSUE TITLE
Need to sync to latest providers list

### ISSUE THREAD

**Issue by amyjchen** [ndaidong/oembed-parser#153]
Hey! Love this library — would you be able to sync to the latest providers list? The current version is missing the TikTok profile embed scheme.

**Comment by ndaidong** [comment]
@amyjchen ok, thank you. I don't see that my [related pr](https://github.com/iamcal/oembed/pull/671) has been merged :smile:

**Comment by amyjchen** [comment]
Awesome, thank you!
