### ISSUE TITLE
No support for "youtube-nocookie.com" domains?

### ISSUE THREAD

**Issue by EricSnell** [ndaidong/oembed-parser#157]
Hello! I'm getting an error returned when providing a **youtube-nocookie.com** url. Any chance this can be added to the providers? Thanks 😃

**Comment by ndaidong** [comment]
@EricSnell hello, we are using provider list from [iamcal/oembed](https://github.com/iamcal/oembed), where people can add new provider easily by create the YAML file. If you want to support that domain, please try once 😉

**Comment by EricSnell** [comment]
Thanks @ndaidong -- It looks like I could also set this domain using the `setProviderList` method to override the iamcal/oembed provider list - correct?

**Comment by ndaidong** [comment]
@EricSnell yes, you can.
