### ISSUE TITLE
Improvements for keeping an up-to-date providers.json

### ISSUE THREAD

**Issue by kevinansfield** [ndaidong/oembed-parser#17]
I think it would be useful to make this package easier to use with the latest [providers.json](https://oembed.com/providers.json) source.

A couple of ideas:
1. A package.json script that performs a basic request to update the `package.json` file in this package (quicker publishing)
2. Ability to pass in a custom providers list to the `hasProvider` and `extract` methods
    - allows module consumers to keep their own providers.json file up to date

**Comment by ndaidong** [comment]
thanks for your idea. I would consider to implement these useful things.
