### ISSUE TITLE
node-fetch problem when using on the server

### ISSUE THREAD

**Issue by Pavel910** [ndaidong/oembed-parser#26]
I tried using this library on the server, and there seems to be a problem with how `node-fetch` is imported, I get `fetch is not a function`.

Looking for a possible solution I found this: https://github.com/bitinn/node-fetch/issues/450

Tried the suggested `const fetch = require('node-fetch').default;` locally, and it really works.

I think it would be a great addition to the library to also support usage in non-browser environments.
Cheers!

**Comment by ndaidong** [comment]
@Pavel910 thanks, let's I try.
