### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by mehmetkose** [ndaidong/oembed-parser#44]
![cors](https://user-images.githubusercontent.com/706678/62296927-cffc3b80-b478-11e9-9003-83c24baec870.png)

I think we need to add some headers

**Comment by ndaidong** [comment]
@mehmetkose could you provide the URL you've passed to oembed-parser, I believe that the oembed provider always enabled CORS because that's public service.

**Comment by mehmetkose** [comment]
Uh now it's working, I'm not sure how I got there. Thanks anyway!

**Comment by mehmetkose** [comment]
Uh now it's working, I'm not sure how I got there. Thanks anyway!
