### ISSUE TITLE
Breaking behavior after fetchEmbed refactor to async syntax

### ISSUE THREAD

**Issue by gargol** [ndaidong/oembed-parser#46]
This wasn't explicitly communicated in the latest 1.3.0 release, so wanted to clarify that that new behavior was intended :smiley:

The breaking changes were introduced in https://github.com/ndaidong/oembed-parser/commit/70f36f374d5b4327b90336855d160b3a7d11e0a7#diff-177c6ce64f7c942009c667a943836a36R26-R27

**Previously** the error was rethrown giving the library client the ability to handle it. 
**Currently** when the error occurs the log output gets polluted with `console.trace` and there is no way to distinguish if the response was `null` or it's a result of an error.

Think leaving the `try/catch` block out would be more flexible behavior and more compatible with the previous interface. @ndaidong, thanks in advance and would love to hear your opinion!

For context, this change blocks Ghost from making an upgrade (https://github.com/TryGhost/Ghost/pull/10983) due to [this test](https://github.com/TryGhost/Ghost/blob/renovate/oembed-parser-1.x/core/test/unit/api/v0.1/oembed_spec.js#L127-L140) failing.

**Comment by ndaidong** [comment]
@gargol I see the problem. Removing try/catch block and leaving the exception for consumer may be good choice for right now.

**Comment by gargol** [comment]
@ndaidong would it help if I create a PR for this or it's easier for you to commit this small change straight to master?

**Comment by ndaidong** [comment]
@gargol I'm going to release v1.3.1, please help me verify if it resolves the problem you mentioned. Thanks.

**Comment by gargol** [comment]
sure thing @ndaidong! and thanks a lot for such a prompt response :wink:

**Comment by ndaidong** [comment]
@gargol I just published oembed-parser@1.3.1 to npmjs
Please let's me know if it does not help. I'm one of the first fans of Ghost :)

**Comment by gargol** [comment]
The build with 1.3.1 has passed :tada: https://github.com/TryGhost/Ghost/pull/10983 Thank you!!!

**Comment by ndaidong** [comment]
@gargol my pleasure :)
