### ISSUE TITLE
Missing dependency `debug` in production mode. 

### ISSUE THREAD

**Issue by kub1x** [ndaidong/oembed-parser#50]
Dependency `debug` is always used. Should be `dependency` not `devDependency`. 

Edit: 
Just noticed it could be just removed from `src/utils/index.js`, as it is never used that way anyway. 

I've encountered this when `oembed-parser` was installed as a dependency of other package. When using pnpm which doesn't leak dependencies like npm does.

**Comment by ndaidong** [comment]
@kub1x thank you. Actually this library does not use `debug` anywhere. We should remove  `debug` from src/utils/index.js to avoid issue on the environment where there is no `debug` installed. Will be fixed now.
