### ISSUE TITLE
Fetch not following redirect 302

### ISSUE THREAD

**Issue by ferjgar** [ndaidong/oembed-parser#70]
Hello! Thanks for your work. I'm trying to use it with a simple example like this:

```
import React, { useState, useEffect } from 'react';
import { extract, OembedData } from 'oembed-parser';

const TEST_URL = 'https://www.instagram.com/p/CDMX_OBn9s2/';

const Card = (): React.ReactElement => {
  const [oembedData, setOembedData] = useState<OembedData>();

  useEffect(() => {
    const fetchData = async () => {
      const result = await extract(TEST_URL);
      setOembedData(result);
    };

    fetchData();
  }, []);

  return <div>{oembedData}</div>;
};

export default Card;
```

But getting an error on fetching:

```
fetchEmbed.js:36 Uncaught (in promise) SyntaxError: Unexpected end of input
    at fetchEmbed (fetchEmbed.js:36)
    at async extract (main.js:21)
    at async fetchData (SocialMediaCard.tsx:10)
```

The Instagram API is doing some 302 redirects, and looks like `fetch` is not following `type: "opaque"` requests.

But using the same url in https://ndaidong.github.io/oembed-parser-demo/ works well! So I'm not sure if I'm missing something.

I'm using `node v14.2.0` and `oembed-parser v1.4.0`.

Thanks!

**Comment by ndaidong** [comment]
@ferjgar a quick test shows that it works well for your link. It looks like the problem occurs only with TypeScript.

![Screenshot from 2020-08-05 22-39-41](https://user-images.githubusercontent.com/1809619/89433647-c9c82b80-d76c-11ea-9867-a947df3db74a.png)

**Comment by ferjgar** [comment]
Yeah, isolated works, looks like the problem is React, I've tried a simple example here with the same error result: https://codesandbox.io/s/react-live-sandbox-y9ozx?file=/src/components/App.js.
