### ISSUE TITLE
SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by abdalmonem** [ndaidong/oembed-parser#73]
the extract always catch : 
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by abdalmonem** [comment]
removing : `mode: 'no-cors'` , from 'fetchEmbed.js' stop the error

**Comment by ndaidong** [comment]
@abdalmonem which url or domain given you that issue? I don't see that happens for me.

**Comment by abdalmonem** [comment]
a youtube url and twitter url , in a local host , i dont try it on live domain

**Comment by ndaidong** [comment]
can you share your code? could you clone this repo, install and try `npm run eval YOUR_URL`?

**Comment by tylershuster** [comment]
I also get this error, using the example code..

I'm running in the browser context, and I expect @abdalmonem also is. This is not a backend application.

Inspecting the result of the fetch shows that the information is received.

**Comment by ndaidong** [comment]
@tylershuster this lib doesn't support browser context. I've tried a few ways, even with [Skypack](https://www.skypack.dev/), but could not get it works there.

**Comment by tylershuster** [comment]
Ok. It might be the browser blocking the cors request

**Comment by araphiel** [comment]
This explains a lot, I was under impression this could be used on the browser.

**Comment by tylershuster** [comment]
Try using https://noembed.com/ in the browser. It allows CORS requests.

**Comment by ndaidong** [comment]
hi there, [noembed.com](https://noembed.com/) suggested by @tylershuster could be good choice for client usage. If you don't like JSONP, you can setup [oembed-parser](https://github.com/ndaidong/oembed-parser) on your own Node.js server and use it as proxy.

I would like to close this issue. Please feel free to create new one if any other problem with this lib.
