### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by IGMontero** [ndaidong/oembed-parser#75]
Hey, lately I've been having issues retrieving link data from Instagram links after deploying my app. The library is extracting the data correctly when testing it locally.

For instance, this is a problematic url: https://www.instagram.com/p/Bxm4oscl5uw/?igshid=1g2yro3jcf5r5

Example error response:

Error in oembed parser:  FetchError: invalid json response body at https://api.instagram.com/oembed/?format=json&url=https://www.instagram.com/p/Bxm4oscl5uw/?igshid=1g2yro3jcf5r5 reason: Unexpected token T in JSON at position 0
0|npm  |     at /home/ubuntu/hfplatform-back-end/node_modules/node-fetch/lib/index.js:272:32
0|npm  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|npm  |     at async fetchEmbed (/home/ubuntu/hfplatform-back-end/node_modules/oembed-parser/src/utils/fetchEmbed.js:33:16)
0|npm  |     at async extract (/home/ubuntu/hfplatform-back-end/node_modules/oembed-parser/src/main.js:21:16)
0|npm  |     at async Object.commonServices.scrapUrl (/home/ubuntu/hfplatform-back-end/src/services/commonServices.js:68:22) {
0|npm  |   message: 'invalid json response body at https://api.instagram.com/oembed/?format=json&url=https://www.instagram.com/p/Bxm4oscl5uw/?igshid=1g2yro3jcf5r5 reason: Unexpected token T in JSON at position 0',
0|npm  |   type: 'invalid-json'
0|npm  | }

Thanks!

**Comment by MarcMcIntosh** [comment]
maybe related to #74

**Comment by ndaidong** [comment]
@IGMontero @MarcMcIntosh thank you. I will try to fix this issue in the next release.

**Comment by ndaidong** [comment]
@IGMontero this issue has been fixed at v1.4.2, please give it a try. Thanks.
