### ISSUE TITLE
Browser CORS issue: no response body returned with `mode: no-cors` 

### ISSUE THREAD

**Issue by ricokahler** [ndaidong/oembed-parser#82]
I was trying to use this lib in the browser but it fails to read the embed because of the `mode: no-cors` here:

https://github.com/ndaidong/oembed-parser/blob/f8181a128e99ec5de774b8f929e2409725c92ced/src/utils/fetchEmbed.js#L46

[According to MDN:](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#Value)

> no-cors — Prevents the method from being anything other than HEAD, GET or POST, and the headers from being anything other than simple headers. If any ServiceWorkers intercept these requests, they may not add or override any headers except for those that are simple headers. **In addition, JavaScript may not access any properties of the resulting Response.** This ensures that ServiceWorkers do not affect the semantics of the Web and prevents security and privacy issues arising from leaking data across domains.

This makes it so that `response.json()` does not receive any data.

**Comment by ndaidong** [comment]
@ricokahler I've tried to make this lib works on the browser side but failed. What did you actually do? Could you share your code?

**Comment by ricokahler** [comment]
Oh sorry, I should've closed this one. Even though I was using it in the browser it doesn't really make sense to because most providers don't allow CORS or handle CORS headers anyway.

I would actually recommend you update your docs to specific that should be a backend-only lib and then you can remove all the `mode: no-cors` stuff because it's irrelevant on the server.

**Comment by ndaidong** [comment]
@ricokahler thank you, I will update the doc.
