### ISSUE TITLE
Type of cache_age should be number, not string

### ISSUE THREAD

**Issue by tremby** [ndaidong/oembed-parser#85]
I'm borrowing this package just for the typings.

I noticed that the `cache_age` key is set as a string, but in many of the responses I'm getting (such as from Flickr) this comes back as a number.

Perhaps it should be number, or perhaps `string | number`?

**Comment by ndaidong** [comment]
@tremby I'm not sure about this property. This lib does nothing with the properties and data type.
As what I've found, `cache_age` is an optional property and can be `string` or `number`. It's often `number` when the format is XML, and `string` when the format is JSON.

**Comment by tremby** [comment]
The XML representation of oembed doesn't even differentiate between string and number, does it? You get `<cache_age>33</cache_age>` and nothing there says whether it's string or number. All the spec seems to say is that it's "in seconds".

All JSON responses I've seen so far have had it as a number rather than a string.

Regardless, given that in the wild it *can* be either, having it typed as `string | number` would be useful, since it'll pop up errors if the code is only handling it as a string or only as a number.

**Comment by ndaidong** [comment]
Got it. I will update relevant type definition.

**Comment by tremby** [comment]
Thanks!
