### ISSUE TITLE
.{format} fragment of some provider endpoint urls breaks requests

### ISSUE THREAD

**Issue by danscan** [ndaidong/oembed-parser#9]
When attempting to use a provider with `.{format}` in its endpoint url, the request is unsuccessful.

I think that `.{format}` is meant to be replaced with a format value, like `.json`. This doesn't seem to be working.

An acceptable fix might be to just replace all occurrences of `.{format}` in `providers.json` with `.json`.  I'm happy to do a PR if that is acceptable :)

**Comment by ndaidong** [comment]
Thank you for pointing that. A little modification here might be useful. Please do a PR. I appreciate every contribution.

**Comment by danscan** [comment]
@ndaidong Awesome, thanks :)  Here's a PR: https://github.com/ndaidong/oembed-parser/pull/10

**Comment by danscan** [comment]
@ndaidong Thank you for merging :) Are you able to `npm publish` `1.0.6`?

**Comment by ndaidong** [comment]
@danscan thank you so much. I've checked and merged. New version will come to npmjs in few minutes.
