### ISSUE TITLE
Failed to fetch youtube

### ISSUE THREAD

**Issue by gaberoffman** [ndaidong/oembed-parser#90]
Would return an empty response.

But when I removed ` {mode: 'no-cors'}` from the `fetch` call to the provider, it worked just fine

**Comment by ndaidong** [comment]
@gaberoffman thank you, I will find the root cause here.

**Comment by ndaidong** [comment]
@gaberoffman I've checked and it extracts youtube links as well. Could you share the urls those didn't work for you?

**Comment by Rupenieks** [comment]
@ndaidong Hey man, I had the same issue. I just removed `{mode: 'no-cors}` and it worked fine. 

Youtube link: https://www.youtube.com/watch?v=GpMP6Nh3FvU

**Comment by ndaidong** [comment]
@Rupenieks I see that it works fine on [the demo](https://ndaidong.github.io/oembed-parser-demo/) too.

**Comment by Rupenieks** [comment]
@ndaidong Hey, I've set up a codesandbox to demonstrate:

https://codesandbox.io/s/cocky-tree-ju5o6?file=/src/index.js

![brave_9rYWuq8hMm](https://user-images.githubusercontent.com/32895755/117144127-dcca6380-adb1-11eb-9425-bc2c25eae941.png)

**Comment by ndaidong** [comment]
@Rupenieks it seems the code is running in the browser. Only node environment supported at this time because `fetch`'s limitation.
