### ISSUE TITLE
Bug: Maybe due to node-fetch

### ISSUE THREAD

**Issue by andre-dietrich** [ndaidong/oembed-parser#93]
Hi, first of all, great lib... I had to go back to version 1.3.2 to have a working version within the browser. For all later versions I get the following error:

**`SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`**

This is the result of the catch of the following peace of code 

```js
extract(url, options).then(json => {
   ...
}).catch(err => {
   console.warn(err)
}
```

I think this may be caused by the switch from cross-fetch to node-fetch ...

Regards

André

**Comment by ndaidong** [comment]
@andre-dietrich thank you for your feedback and sorry for late response.

In the past, I've tried to make this lib works within the browser by replacing node-fetch with cross-fetch, however it doesn't work. So I decided to focus on server environment only. I'm not sure that if you can use this on the browsers.

**Comment by andre-dietrich** [comment]
Hi, I am using it within the browser and it works good, with cross-fetch ... The video shows a live application, every Markdown link that starts with two question-marks makes use of your project ;-) 

https://www.youtube.com/watch?v=hcHCUN-kZaA

The only thing that is sometimes not working, is when CORS comes in, recently i discovered JSONP, which might be useful to deal with such problems in the future ...

Regards ...

**Comment by ndaidong** [comment]
@andre-dietrich thank you, itt's exactly that the problem with CORS I've met. 
JSONP is a good approach to by pass CORS problem at client side. But it requires a little support from server side to response data within function call expression. Do you any plan to deal with that?

**Comment by andre-dietrich** [comment]
I want to enclose all the work in a webcomponent. At the moment I found a quick and dirty solution, I simply pass the query through http://allorigins.win/ ... since it is only requesting the oembed services, it should not generate to much additional traffic ... Later on, this can be used as a fallback, if the first query did not succeed, the second is passed through this service ...

**Comment by ndaidong** [comment]
@andre-dietrich Cool! Thank you for sharing allorigins.win, it's great solution if you don't worry about privacy. Otherwise, you should setup a proxy server for yourself.
