### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [ndaidong/oembed-parser#95]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ndaidong** [comment]
@zidingz thank you for your suggestion. I missed this best practice. Security policy for this lib will be added asap.

**Comment by ndaidong** [comment]
@zidingz the security policy is now available [here](https://github.com/ndaidong/oembed-parser/security/policy). Pleae send me your report to security-report@pwshub.com if any. Thanks.
